### ISSUE TITLE
Modular Upload bug

### ISSUE THREAD

**Issue by jean-louis-git** [vaadin/flow-components#9845]
### Description

Hi ... the Modular Upload works with firefox on android, but not with chrome or the samsung browser... also the iphone opens no camera or a file manager ... -> just firefox works .. any ideas? we work with 25.2.5 ... 
console: indexhtml-DTWfpmLU.js:59220 Uncaught TypeError: this._$changeProperty is not a function
    at _ConnectionIndicator.init (indexhtml-DTWfpmLU.js:59220:29)
    at __runInitializers (indexhtml-DTWfpmLU.js:59426:126)
    at new _ConnectionIndicator (indexhtml-DTWfpmLU.js:59488:36)
    at _ConnectionIndicator.create (indexhtml-DTWfpmLU.js:59527:48)
    at get instance (indexhtml-DTWfpmLU.js:59517:32)
    at indexhtml-DTWfpmLU.js:59892:22
    at chunk-BY_RDDpE.js:8:49
    at indexhtml-DTWfpmLU.js:59905:2
    at chunk-BY_RDDpE.js:8:49
    at indexhtml-DTWfpmLU.js:60500:2

### Expected outcome

That the filemanager or the camera opens to upload some files.

### Minimal reproducible example

[BaseUploadFragment.java](https://github.com/user-attachments/files/30787780/BaseUploadFragment.java)

[ImageUploadFragment.java](https://github.com/user-attachments/files/30788086/ImageUploadFragment.java)

### Steps to reproduce

try the code

### Environment

Vaadin version(s): 25.2.5
OS: Android 16 und and IPhone 17

**Comment by jean-louis-git** [comment]
It seems that the vaadin-button-container is not reacting ... the borders (if you find some pixels -> could take some tries) are working, but not the middle (container)

**Comment by tomivirkki** [comment]
Based on the error message, could be related to https://github.com/vaadin/flow/issues/23944

**Comment by yuriy-fix** [comment]
We could verify if the issue persists once https://github.com/vaadin/flow/issues/23944 is fixed.

**Comment by jean-louis-git** [comment]
We solved the problem:
"@polymer/polymer/polymer-legacy.js" creates that problem ... 
We removed the grid-pagination, which was imported with side project, so we just excluded it, until it is removed (exclude(group = "org.vaadin.klaudeta", module = "grid-pagination")).
And the [clipboardhelper](org.vaadin.olli:clipboardhelper:2.1.0) was removed ... Vaadin has its own, so we removed org.vaadin.olli:clipboardhelper:2.1.0, and will will use com.vaadin.flow.component.clipboard.Clipboard
