### ISSUE TITLE
 Combo Box: this._setOverlayItems is not a function

### ISSUE THREAD

**Issue by TorstenKruse** [vaadin/flow-components#5053]
### Description

We are using MultiComboBox from com.vaadin.componentfactory:multi-combo-box-flow
After update of Vaadin from 23.1 to 23.3 we get the following JS error and all MultiComboBox controls are displayed without content and not clickable.

JS error is:
Uncaught TypeError: this._setOverlayItems is not a function (http://localhost:8080/VAADIN/@fs/E:/Projects_git/alv/modules/application/node_modules/.vite/deps/@vaadin-component-factory_vcf-multiselect-combo-box_src_vcf-multiselect-combo-box__js.js?v=9b3452ae:149:8)
There seems to be an error in Vaadin Combo Box: this._setOverlayItems is not a function Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, return $0.$connector.updateSize($1)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, $3, return $0.$connector.set($1,$2,$3)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, return $0.$connector.confirm($1,$2)'
Uncaught TypeError: $0.$connector.updateSize is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Uncaught TypeError: $0.$connector.set is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Uncaught TypeError: $0.$connector.confirm is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, if($0.$connector) $0.$connector.reset();'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, return $0.$connector.updateSize($1)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, $3, return $0.$connector.set($1,$2,$3)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, return $0.$connector.confirm($1,$2)'
Uncaught TypeError: $0.$connector.reset is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Uncaught TypeError: $0.$connector.updateSize is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Uncaught TypeError: $0.$connector.set is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)
Uncaught TypeError: $0.$connector.confirm is not a function (http://localhost:8080/VAADIN/generated/jar-resources/FlowClient.js:207:16)

### Expected outcome

MultiComboBox should work as in former vaadin 23.1

### Minimal reproducible example

Just add a simple
private MultiComboBox<LovEntity> comboBox;
to your form and view it.

### Steps to reproduce

use example from above in a form

### Environment

Vaadin version(s): 23.3
OS:  Windows

**Comment by sissbruecker** [comment]
The VCF MultiSelectComboBox is not an officially supported component, nor is it maintained in this repository.

As of 23.3, the platform includes an official version of the component, although with a few differences regarding supported features: https://vaadin.com/docs/v23/components/multi-select-combo-box

You can consider switching to the official component, or opening an issue in the respective repository for the community addon.

**Comment by knoobie** [comment]
Add-on ticket is already present: https://github.com/vaadin-component-factory/multiselect-combo-box/issues/28
