### ISSUE TITLE
Vaadin 23.2 binary-incompatible with 23.1

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#3423]
### Description

Vaadin 23.2 is binary-incompatible with 23.1:
```
'void com.vaadin.flow.component.button.Button.addThemeVariants(com.vaadin.flow.component.button.ButtonVariant[])'
java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.button.Button.addThemeVariants(com.vaadin.flow.component.button.ButtonVariant[])'
	at com.github.mvysny.karibudsl.v10.VaadinComponentsKt$iconButton$2.invoke(VaadinComponents.kt:51)
	at com.github.mvysny.karibudsl.v10.VaadinComponentsKt$iconButton$2.invoke(VaadinComponents.kt:50)
```
I like the new HasThemeVariant, but for compatibility reasons the components should redeclare the addThemeVariants() functions, to keep binary compatibility with libraries targeting both Vaadin 23.1 and 23.2.

### Expected outcome

The code compiled against Vaadin 23.1. should work with Vaadin 23.2.

### Minimal reproducible example

-

### Steps to reproduce

-

### Environment

Vaadin version(s): 23.2.0.alpha1
OS:
