### ISSUE TITLE
ComponentRenderer default configuration leads to bad practices, subtle bugs

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#3901]
### Describe your motivation

Currently the easiest way to define a component renderer is to just pass a function for creating the DOM structure:
```java
grid.addColumn(new ComponentRenderer<>(item -> {
  Span label = new Span(item.getLabel());
  label.addClassName("my-label");
  return label;
}));
```

With this configuration the component renderer will recreate it's DOM every time a re-render is triggered, for example when calling `Grid.refreshItem`, `Grid.refreshAll` or even `Grid.select`. In order to have the renderer not discard the DOM on every update, an update function needs to be implemented for the component renderer as well.

The problem I see is that the component renderer makes it too easy to use this discard-and-recreate behavior which can lead to subtle / hard to discover bugs when a rerender is triggered. Recent examples:
- https://github.com/vaadin/flow-components/issues/3897 - Server-side selection causes a rerender of the row details. Row details contain stateful components (inputs, tabs) that are now reset (user input is lost) because the whole DOM is recreated. Developer is not aware that component renderer even supports an update function.
- https://github.com/vaadin/flow-components/issues/2266 - Server-side selection causes a rerender of column cells. Due to discarding the old DOM, any pending events coming from that DOM in the same server roundtrip are discarded as well. Developer did not implement an update function either.

Apart from these specific examples, having component renderers recreate the DOM on every render can lead to performance issues, especially when using `Grid.refreshAll`, which is also conveniently easy too use.

### Describe the solution you'd like

I have no specific proposal in mind, only a general feeling that component renderer makes it a bit too convenient to opt-in into the recreate behavior. While the current APIs make it very easy to get started, they can lead to bad practices around performance, hide the fact that update is even supported, and lead to subtle bugs such as the ones mentioned above.

Some random ideas on how to improve the situation:
- Make developers explicitly opt-in into the recreate behavior
- Log warning when using a component renderer that does not implement updates, provide way to opt-out of the warning, for example by adding a constructor flag that indicates you really want this behavior
- Make it more obvious that implementing an update function is supported
- Improve docs

**Comment by yuriy-fix** [comment]
We could start approaching it with updating documentation examples, so that we are providing the `componentUpdateFunction` that returns the same component with a comment that it will avoid unnecessary  re-rendering of the component. 

@mshabarov, do you think it worth discussing it further with the Flow team, so we could come up with a better approach to `ComponentRenderer`s

**Comment by tomivirkki** [comment]
The `ComponentRenderer` with a `componentUpdateFunction` has a couple of oddities worth noting:
1. When the component is first created, the update function isn't automatically invoked for it. As a result, you either need to duplicate the update logic in both the creation and update functions, or extract the logic into a shared helper function and call it from both.
2. The component parameter in the update function is typed as a generic `Component`, meaning you’ll have to cast it to the correct type.

```java
grid.addColumn(new ComponentRenderer<Icon, Person>(person -> {
    var icon = new Icon();
    icon.getElement().getThemeList().add("badge");
    icon.getStyle().set("padding", "var(--lumo-space-xs");

    // 1. The component needs to be updated here also
    var isSubscriber = person.isSubscriber();
    icon.setIcon(isSubscriber ? VaadinIcon.CHECK : VaadinIcon.CLOSE_SMALL);
    icon.getElement().getThemeList().set("success", isSubscriber);
    icon.getElement().getThemeList().set("error", !isSubscriber);

    return icon;
}, (icon, person) -> {
    var isSubscriber = person.isSubscriber();
    // 2. The component needs to be cast to the correct type
    ((Icon)icon).setIcon(isSubscriber ? VaadinIcon.CHECK : VaadinIcon.CLOSE_SMALL);
    icon.getElement().getThemeList().set("success", isSubscriber);
    icon.getElement().getThemeList().set("error", !isSubscriber);
    return icon;
})).setHeader("Subscriber");
```

These issues could likely be resolved without breaking existing behavior, and doing so would make the update function more straightforward to use.

**Comment by DiegoCardoso** [comment]
> 2\. The component parameter in the update function is typed as a generic `Component`, meaning you’ll have to cast it to the correct type.

I was trying to understand this as to why it wasn't typed with the first generic parameter, and my understanding is that it would allow the developer to change the cell with a new component type (e.g. a `TextField` to a `Span`). Not sure if this is the actual reason for this decision.

**Comment by tomivirkki** [comment]
> it would allow the developer to change the cell with a new component type (e.g. a TextField to a Span)

I guess you could still change the type if you expliclitly used `new ComponentRenderer<Component, Person>`

**Comment by yuriy-fix** [comment]
Let's update the Component Renderer section on Grid docs page to mention availability and the purpose of the update callback (code snippet and possibly an admonition describing the behaviour)
