### ISSUE TITLE
PiT 25.2: Slider/RangeSlider removal is a breaking change in a minor version, should be deprecated first

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#9218]
### Description of the bug

PR #9171 removed the `Slider`, `RangeSlider`, and `RangeSliderValue` classes in 25.2.0-alpha4, renaming them to `DecimalSlider`, `DecimalRangeSlider`, and `DecimalRangeSliderValue`. The old class names were removed without deprecation.

This is a **breaking change in a minor version** (25.2). Semver specifies that minor versions should only add features, not remove existing APIs. Existing user code that uses `Slider`, `RangeSlider`, or `RangeSliderValue` no longer compiles after upgrading from 25.1 to 25.2.

For comparison, the `SpringBrowserlessTest` migration in 25.1 was handled correctly: the old class was kept as `@Deprecated(forRemoval = true)` while the new class was introduced in a new package.

### Expected behavior

The old classes should be retained as deprecated aliases delegating to the new ones:

```java
@Deprecated(forRemoval = true)
public class Slider extends DecimalSlider { }

@Deprecated(forRemoval = true)
public class RangeSlider extends DecimalRangeSlider { }

@Deprecated(forRemoval = true)
public class RangeSliderValue extends DecimalRangeSliderValue { }
```

This allows existing code to compile with a deprecation warning, giving users time to migrate.

### Impact

Discovered during PiT testing. The `expo-flow` demo fails to compile with 25.2.0-alpha4:

```
cannot find symbol: class RangeSlider
cannot find symbol: class RangeSliderValue
cannot find symbol: class Slider
```

### Versions

- Vaadin / Flow version: 25.2.0-alpha4
- Introduced in: PR #9171

**Comment by manolo** [comment]
Closing this. The Slider component is under a **feature flag** (`sliderComponent`) and marked as experimental since its introduction (see `SliderFeatureFlagProvider`). Experimental APIs are exempt from the semver stability contract and can change without deprecation.

That said, it would be helpful to add a note in the release notes or migration guide for 25.2 mentioning the rename (`Slider` -> `DecimalSlider`, `RangeSlider` -> `DecimalRangeSlider`, `RangeSliderValue` -> `DecimalRangeSliderValue`), so users who opted into the experimental feature know what to update.
