### ISSUE TITLE
Gantt Chart doesn't work in dev mode with Vaadin 25.1.0

### ISSUE THREAD

**Issue by F-Kamp** [vaadin/flow-components#9039]
### Description

After updating to Vaadin 25.1.0 the Gantt Chart component doesn't seem to work anymore when running the application in dev mode. This is printed to the browser console:

```text
GanttResult:8 Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
GanttResult:8 The error has occurred in the JS code: '$0, $1, $2, return $0.updateConfiguration($1,$2)'
FlowClient-UiW1Q_9Y.js:349 Uncaught TypeError: $0.updateConfiguration is not a function
    at Object.eval (eval at Du (FlowClient-UiW1Q_9Y.js:7478:13), <anonymous>:3:11)
    at Du (FlowClient-UiW1Q_9Y.js:7479:11)
    at Cu (FlowClient-UiW1Q_9Y.js:6117:7)
    at Au (FlowClient-UiW1Q_9Y.js:2405:9)
    at Tr (FlowClient-UiW1Q_9Y.js:1766:7)
    at os.ps [as fb] (FlowClient-UiW1Q_9Y.js:8756:7)
    at uC (FlowClient-UiW1Q_9Y.js:5681:28)
    at Wr (FlowClient-UiW1Q_9Y.js:7606:9)
    at ks.ls [as C] (FlowClient-UiW1Q_9Y.js:8745:7)
    at cl (FlowClient-UiW1Q_9Y.js:3817:15)
    at jl.ll [as eb] (FlowClient-UiW1Q_9Y.js:8200:7)
    at fo.go [as I] (FlowClient-UiW1Q_9Y.js:8437:14)
    at FlowClient-UiW1Q_9Y.js:5433:14
```
The Gantt is not displayed in the browser at all.

Funnily enough, when running in production mode, everything works fine - Gantt is displayed and Gantt items are drawn.

### Expected outcome

Dev mode should work

### Minimal reproducible example

```kotlin
@Route("Demo")
class GanttDemo : Div() {

    init {
        val chart = Chart(ChartType.GANTT)
        val configuration = chart.configuration
        
        val projectDevelopmentSeries = createProjectDevelopmentSeries()
        configuration.addSeries(projectDevelopmentSeries)

        add(chart)
    }

    private fun createProjectDevelopmentSeries(): GanttSeries {
        val series = GanttSeries()
        series.name = "Project 1"


        val item = GanttSeriesItem(0, Instant.now(), Instant.now().plusSeconds(12000))
        series.add(item)

        return series
    }
}
```

### Steps to reproduce

Run the application in dev mode and navigate to /Demo

### Environment

- Vaadin / Flow version: 25.1.0
- Java version: 21
- OS version: Windows 11
- Application Server (if applicable): Quarkus 3.32.3

### Browsers

Chrome
